#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

git submodule sync --recursive
git submodule update --init --recursive \
  third_party/expat \
  third_party/netsurf/src/libwapcaplet \
  third_party/netsurf/src/libparserutils \
  third_party/netsurf/src/libhubbub \
  third_party/netsurf/src/libcss \
  third_party/netsurf/src/libdom \
  third_party/netsurf/src/libnsutils \
  third_party/netsurf/src/libsvgtiny \
  third_party/netsurf/src/netsurf

if [ ! -f third_party/netsurf/src/libparserutils/src/charset/aliases.inc ]; then
  (cd third_party/netsurf/src/libparserutils && perl build/make-aliases.pl)
fi

if [ ! -f third_party/netsurf/src/libhubbub/src/tokeniser/entities.inc ]; then
  (cd third_party/netsurf/src/libhubbub && perl build/make-entities.pl)
fi

if [ ! -f third_party/netsurf/src/libhubbub/src/treebuilder/autogenerated-element-type.c ]; then
  if command -v gperf >/dev/null 2>&1; then
    (
      cd third_party/netsurf/src/libhubbub
      gperf --output-file=src/treebuilder/autogenerated-element-type.c.tmp src/treebuilder/element-type.gperf
      sed -e 's/^\(const struct element_type_map\)/static \1/' \
        src/treebuilder/autogenerated-element-type.c.tmp \
        > src/treebuilder/autogenerated-element-type.c
      rm -f src/treebuilder/autogenerated-element-type.c.tmp
    )
  else
    perl - third_party/netsurf/src/libhubbub/src/treebuilder/element-type.gperf \
      third_party/netsurf/src/libhubbub/src/treebuilder/autogenerated-element-type.c <<'PERL'
use strict;
use warnings;

my ($input, $output) = @ARGV;
open my $in, '<', $input or die "Unable to open $input: $!";
open my $out, '>', $output or die "Unable to open $output: $!";

my @entries;
my $in_table = 0;
while (my $line = <$in>) {
    if ($line =~ /^%%\s*$/) {
        $in_table = !$in_table;
        next;
    }
    next unless $in_table;
    next if $line =~ /^\s*$/;
    chomp $line;
    my ($name, $type) = split /\s*,\s*/, $line, 2;
    next unless defined $name && defined $type;
    $name =~ s/^\s+|\s+$//g;
    $type =~ s/^\s+|\s+$//g;
    push @entries, [$name, $type];
}

print {$out} <<"EOF";
/* Auto-generated by scripts/bootstrap-browser-deps.sh. */

static unsigned char hubbub_element_type_generated_lower(unsigned char ch)
{
    if (ch >= 'A' && ch <= 'Z') {
        return (unsigned char)(ch + ('a' - 'A'));
    }
    return ch;
}

static int hubbub_element_type_generated_equal(const char *str, size_t len,
        const char *candidate)
{
    size_t i;

    for (i = 0; i < len && candidate[i] != '\\0'; ++i) {
        if (hubbub_element_type_generated_lower((unsigned char) str[i]) !=
                hubbub_element_type_generated_lower((unsigned char) candidate[i])) {
            return 0;
        }
    }

    return i == len && candidate[i] == '\\0';
}

static const struct element_type_map wordlist[] = {
EOF

for my $entry (@entries) {
    print {$out} qq(    { "$entry->[0]", $entry->[1] },\n);
}

print {$out} <<"EOF";
};

static const struct element_type_map *hubbub_element_type_generated_lookup(
        const char *str, size_t len)
{
    size_t i;

    for (i = 0; i < sizeof(wordlist) / sizeof(wordlist[0]); ++i) {
        if (hubbub_element_type_generated_equal(str, len, wordlist[i].name)) {
            return &wordlist[i];
        }
    }

    return NULL;
}
EOF
PERL
  fi
fi

props_dir=third_party/netsurf/src/libcss/src/parse/properties
if [ ! -f "$props_dir/autogenerated_background_color.c" ]; then
  mkdir -p build/third_party/netsurf/libcss
  gcc "$props_dir/css_property_parser_gen.c" -o build/third_party/netsurf/libcss/gen_parser
  perl -ne 'next if /^#/; next unless /^([^:]+):/; print "$1\n"' "$props_dir/properties.gen" |
    while read -r prop; do
      line="$(grep "^${prop}:" "$props_dir/properties.gen")"
      build/third_party/netsurf/libcss/gen_parser -o "$props_dir/autogenerated_${prop}.c" "$line"
    done
fi
